---

- name: Instalando pacotes
  hosts: all
  tasks:
   - name: Instalando pacotes no Debian
     apt:
      name: "{{ item }}"
      state: present
     with_items:
      - vim
      - nano
      - sl
      - ccze
      - dnsutils
