- name: Instalando pacotes (requisitos)
  apt:
   name: "{{ item }}"
   update_cache: yes
  with_items:
    - apt-transport-https
    - ca-certificates
    - curl
    - software-properties-common

- name: Baixando gpg
  apt_key:
   id: 0EBFCD88
   url: https://download.docker.com/linux/ubuntu/gpg
   state: present

- name: Add no repositorio
  apt_repository:
   repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable
   state: present
